version: '3.8'

services:
  # db:
  #   image: postgres:16.3
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: task_manager
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: P@ssw0rd
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    # command: uvicorn task_manager.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      - DB_NAME=task_manager
      - DB_USER=postgres
      - DB_PASSWORD=P@ssw0rd
      - DB_HOST=host.docker.internal
      - DB_PORT=5434

volumes:
  postgres_data:
